### ISSUE TITLE
Reorganizacja nagłówka

### ISSUE THREAD

**Issue by gravvy23** [io-appteka/appteka#27]
Chcemy zmienić układ i wygląd nagówka.
Co mamy:
![image](https://user-images.githubusercontent.com/37000459/57635422-63734e00-75a7-11e9-9450-cb41ed9d363e.png)

Czego oczekujemy:
![image](https://user-images.githubusercontent.com/37000459/57635389-50607e00-75a7-11e9-9de6-a0a0e818b50d.png)

- [x] zmiana styli
- [x] reorganizacja układu komponentów

**Comment by veronimineral** [comment]
Zmiany wprowadzone, wrzucę później, bo mam problemy ze sprzętem.
